### ISSUE TITLE
Unable to use Cuckoo playbook

### ISSUE THREAD

**Issue by dzh01** [PacktPublishing/Security-Automation-with-Ansible-2#1]
I've been reading your book and have attempted to try to deploy cuckoo, however I keep running into this issue.

ERROR! Syntax Error while loading YAML.

The error appears to have been in '/home/ubuntu/Security-Automation-with-Ansible-2/Chapter09/cuckoo-setup/roles/start-cuckoo/tasks/main.yml': line 18, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  command: "cuckoo web runserver 0.0.0.0:8000"
    args:
    ^ here

exception type: <class 'yaml.parser.ParserError'>
exception: while parsing a block mapping
  in "<unicode string>", line 16, column 3
did not find expected key
  in "<unicode string>", line 18, column 5

**Comment by madhuakula** [comment]
Hello @dzh01 

I just saw this issue,

The fix for this issue is YAML syntax.

Currently I don't have access to this repository and updated the fix for this at https://github.com/madhuakula/security-automation-with-ansible-2

The snippet looks like below

```
- name: starting cuckoo webserver
  command: "cuckoo web runserver 0.0.0.0:8000"
  args:
    chdir: "/root/.cuckoo/web"
  ignore_errors: yes
```

Thanks
